packaging_format = 2

id = "moodle"
name = "Moodle"
description.en = "Online learning platform"
description.fr = "Plateforme d'apprentissage en ligne"

version = "4.0.4io~ynh1"

maintainers = [""]

[upstream]
license = "GPL-3.0-or-later"
website = "https://moodle.org/"
demo = "https://sandbox.moodledemo.net/"
admindoc = "https://docs.moodle.org/400/en/Main_page"
code = "https://github.com/moodle/moodle"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "50M"
ram.build = "2000M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/moodle"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.site_name]
    ask.en = "Choose a name for the site you want to create"
    ask.fr = "Choisissez un nom pour le site que vous voulez créer"
    type = "string"
    default = "Moodle"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/iomad/iomad/archive/refs/tags/IOMAD_404.tar.gz"
        sha256 = "f01d26151738514c7324e4ba54b05e8bac607678724065936e8a7e1ee9b62e63"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql, php8.2-mbstring, php8.2-curl, php8.2-xmlrpc, php8.2-soap, php8.2-zip, php8.2-gd php8.2-xml, php8.2-intl, php8.2-pgsql, php8.2-ldap"

    [resources.database]
    type = "postgresql"
